import Link from 'next/link'
import Image from 'next/image'
import pic from "../components/about.jpeg";
import styles from"../styles/index.module.css"
const aboutPage = ()=>{
  return(
        <><center>
      <Image src={pic}
      alt="picture of the developer"
      width="460px"
      height="400px"
     />
    <h1 className={styles.main_heading}> Tarun Bhan SDE</h1>
      </center>
<p className={styles.para}> 
Velit sit sit labore exercitation cupidatat enim nisi Lorem dolore labore pariatur ad ullamco. Nulla id ex nisi tempor non fugiat cillum reprehenderit proident ut esse. Eiusmod cupidatat reprehenderit enim ut ex ipsum aliqua. Voluptate ut tempor enim irure cupidatat consectetur est reprehenderit. Amet enim commodo dolore nostrud qui ex. Commodo enim non duis dolor velit aliqua incididunt aliquip magna eiusmod enim non labore.
</p>
  
<div className="flex min-h-screen justify-center items-center">
  <head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </head>
    <button className='bg-red-700 hover:bg-sky-700... even:bg-slate-100'>TARUNBHAN </button>
    <button class="dark:md:hover:bg-fuchsia-600... focus:ring">HELP</button>
  <div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
    <img
     className="w-full"
      src="https://tailwindcss.com/img/card-top.jpg"
      alt="Sunset in the mountains"
    />
    <div className="px-6 py-4">
      <div className="font-bold text-xl mb-2">Next + Tailwind 👽❤️</div>
      <p className="text-grey-darker text-base">
        Next and Tailwind CSS are a match made in heaven, check out this article on how
        you can combine these two for your next app.
      </p>
<button class="btn-blue"> find friends</button>
    </div>
  </div>
</div> 
<div className='container'>
<input type="file" class="block w-full text-sm text-slate-500 
file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 
file:text-sm file:font-semiblod file:bg-violet-50 file:text-voilet-700 
hover:file:bg-violet-100"/></div>
{/* <Link href="/">
    <a>Back to Home</a>
    </Link> */}
   
</>
 )
}

export default aboutPage
